# Cloudflare Pages 配置文件
# 也可以直接在 Cloudflare Pages 控制台配置，无需此文件

name = "digital-garden"

[build]
command = "npm run build"

[build.output]
directory = "dist"

# 环境变量（如需要）
[env.production]
NODE_VERSION = "18"

